### ISSUE TITLE
Tuple 4 supported?

### ISSUE THREAD

**Issue by Quafadas** [sherpal/url-dsl#12]
I can't get this to compile.
```
  val claimQueryParams: QueryParameters[(Option[List[String]], Option[List[String]], Option[String], Option[String]), DummyError] = 
     (
        listParam[String]("lossParts").? & 
        listParam[String]("granularity").? & 
        param[String]("startDate").? & 
        param[String]("endDate").?
     )
```
If I remove the last parameter, (and alter the signature), then it seems to work well... here's the compile error.

```
[info] compiling 1 Scala source to C:\temp\ilsclaims\out\frontend\compile.dest\classes ...
[warn] Flag -Xsemanticdb set repeatedly
[error] -- [E007] Type Mismatch Error: C:\temp\ilsclaims\frontend\src\routes.scala:124:8
[error] 124 |        listParam[String]("lossParts").? &
[error]     |        ^
[error]     |Found:    urldsl.language.QueryParameters[?1.Out, urldsl.errors.DummyError]
[error]     |Required: urldsl.language.QueryParameters[(Option[List[String]], Option[List[String]],
[error]     |
[error]     |  Option[String]
[error]     |
[error]     |, Option[String]), urldsl.errors.DummyError]
[error]     |
[error]     |where:    ?1 is an unknown value of type urldsl.language.Tupler.Aux[(Option[List[String]], Option[List[String]],
[error]     |  Option[String]
[error]     |), Option[String], ((Option[List[String]], Option[List[String]], Option[String])
[error]     |  ,
[error]     |Option[String])]
[error] 125 |        listParam[String]("granularity").? &
[error] 126 |        param[String]("startDate").? &
[error] 127 |        param[String]("endDate").?
[error]     |
[error]     | longer explanation available when compiling with `-explain`
```
I think I did manage to get it to compile, essentially by poking around with the tuples... 

```

  val claimQueryParams: QueryParameters[((Option[List[String]], Option[List[String]], Option[String]), Option[String]), DummyError] = 
     (
      (
        listParam[String]("lossParts").? &         
        listParam[String]("granularity").? &
        param[String]("startDate").?
        ) &
        param[String]("endDate").?
     )
     
```
But it's a bit of an odd construct, and the route ends up looking; 
```
decode = args => Page.ClaimReport(args.path, args.params._1._1, args.params._1._2, args.params._1._3, args.params._2),
```
:-D

I'm not sure if that would be expected?

Edir: This appears to throw a runtime error... so perhaps my trick is not so good!

**Comment by sherpal** [comment]
Hum, that's weird. What if you group like this:

```scala
(listParam[String]("lossParts").? & listParam[String]("granularity").?) & 
  (param[String]("startDate").? & param[String]("endDate").?)
```

? So, 2 and 2.

**Comment by Quafadas** [comment]
Bizarrely, that worked. Although I have noticed, that if I split the route out, into a "seperate" queryparams val, rather than encode it directly, then I get a runtime error about null. I don't pretent to understand. But this; 

``` 

  val reportRoute = Route.withQuery[Page.Report, String, (Option[List[String]], Option[List[String]], Option[String], Option[String])](
    encode = page => UrlMatching(path = page.id, params = (page.lossParts, page.granularity, page.startDate, page.endDate)),
    decode = args => Page.ClaimReport(args.path, args.params._1, args.params._2, args.params._3, args.params._4),
    pattern = (uiPath / "claimReport" / segment[String] / endOfSegments) ?       (
        listParam[String]("lossParts").? &
          listParam[String]("granularity").?
      ) &
      (
        param[String]("startDate").?
          & param[String]("endDate").?
      )
  )
```
Compile and runs. 

Splitting out the query param part; 

```

  val claimQueryParams: QueryParameters[(Option[List[String]], Option[List[String]], Option[String], Option[String]), DummyError] = 
(
        listParam[String]("lossParts").? &
          listParam[String]("granularity").?
      ) &
      (
        param[String]("startDate").?
          & param[String]("endDate").?
      )

```
Compiles, but for me appears to generate a runtime error in waypoint. 

Thanks for the help! Time to sleep...

**Comment by raquo** [comment]
@sherpal I think this does not compile because URL DSL is missing an `implicit def tupler3And1[A, B, C, D]: Aux[(A, B, C), D, (A, B, C, D)]` instance of `Tupler`.

Also, the idea of URL-DSL Tupler looks suspiciously similar to @yurique's https://github.com/tulz-app/tuplez which is used in Laminar, except Tuplez does not currently offer an `unapply` method.

**Comment by sherpal** [comment]
Ah yes it's probably this one who is missing.

For the record, I put in the source code from where this implementation is stolen: https://github.com/julienrf/endpoints/blob/7d0af49bc7a83b5985815d936201616ed8a3fa5d/json-schema/json-schema/src/main/scala/endpoints/Tupler.scala

I actually hope that I can make a completely generic implementation in Scala 3, but so far no luck :(

**Comment by raquo** [comment]
Haha sorry I wasn't implying that you "borrowed" it from tuplez, more
suggesting that you might want to use that library

**Comment by yurique** [comment]
> except Tuplez does not currently offer an unapply method

we can have that, just let me know :)

> a completely generic implementation in Scala 3, but so far no luck

At one point I was wondering if tuplez would become obsolete in Scala 3 – it turned out not to be the case (even though Scala 3 does have much more to offer for dealing with tuples than Scala 2 does).

**Comment by sherpal** [comment]
Yes I guess depending on Tuplez is a good idea. The big plus is that in that case we are sure that the behaviour is consistent with signal zipping and related stuff.

But indeed the `unapply` method is necessary :)

**Comment by raquo** [comment]
@yurique Since we all seem to be on the same page here, could you please add `unapply` to Tuplez?

Airstream depends on `tuplez-full-light`, I'm guessing URL-DSL should too, for consistency & to reduce bundle size. I mean as opposed to some other (e.g. `basic` or non-`light`) variation of Tuplez.

**Comment by yurique** [comment]
@raquo sure! I'll look into it today.

**Comment by yurique** [comment]
And of course, the first thing I get is this 👇
<img width="904" alt="image" src="https://user-images.githubusercontent.com/919230/205492884-4a9705b2-de4f-4396-b772-5b16b04880ce.png">

Now I need to remind myself why I made those contravariant 🤔

**Comment by yurique** [comment]
Hmm. Bumped scala to 2.13.10 and now it fails to compile the tests (in the `apply` module):
```
a type was inferred to be `Any`; this may indicate a programming error.
```

**Comment by yurique** [comment]
@raquo @sherpal 

Does this look like something we need here?

https://github.com/tulz-app/tuplez/blob/feature/unapply/modules/basic-light/src/main/scala/app/tulz/tuplez/TupleComposition.scala


Also, I don't know what the usage pattern is for these `unapply` methods, so don't know what kind of tests to generate.

It's being released as `0.4.0-M1` right now.

**Comment by raquo** [comment]
Thanks, I'm trying this locally. Seems to work 👍 I'll send a PR to URL-DSL w/ extra tests shortly.

Now that I looked at this in detail – since tuplez.Composition's main method is called `compose`, maybe we should actually name the new method `decompose` or even `split`, instead of `unapply`?

Seeing that these methods are typically called directly from libraries like Airstream and URL-DSL, there does not seem to be any benefit in using "special" names like `apply` and `unapply`... And our `unapply`'s method signature is no good for use in pattern matching anyway, as it doesn't (and shouldn't) return an Option, so there's no reason it _needs_ to be called `unapply`, as far as I can tell.

ETA: https://github.com/sherpal/url-dsl/pull/14

**Comment by yurique** [comment]
> so there's no reason it _needs_ to be called `unapply`, as far as I can tell

I agree. I'm not changing it just yet – but can do it quickly as soon as we decide to. 

> Seems to work

Awesome! I was concerned (because of not knowing exactly what the use case is :) ) about the fact that while there is just one way to compose two things, there isn't *one* way to decompose:

```
(A, B) ~ (C, D, E) = (A, B, C, D, E)
but also
(A, B, C) ~ (D, E) = (A, B, C, D, E)
```

**Comment by yurique** [comment]
Also, just to emphasize it: the 0.4.x is not binary compatible with 0.3.x. 

But there's a way to make it so (I think).

The change was in the encoding of compose: it was ~like this: 
```scala
val compose: (LEFT, RIGHT) => COMPOSED = ???
```

I changed it to be ~like this:
```scala
def compose(l: LEFT, r: RIGHT): COMPOSED = ???
```

I think I should revert that part and make it `0.3.x` again, or else every lib will have to update to `0.4.x` (Aitstream, waypoint, frontroute, etc).

I would still like to get the `0.4.0` out, with a better encoding, but not sure what the migration plan would be (Laminar 15.x ?)

WDYT?

**Comment by raquo** [comment]
@yurique To be honest my work on 15.0.0 has been consistently proceeding slower than I'd like, so I think it's best to get this fix in 0.14.x. If it's not too much trouble, keeping it binary compatible would be appreciated, but if that's too much work for you, I could release 0.15.0 and rebrand the next big Laminar version as 16.0.0.

I agree that `def` is a better encoding than val long term – it's easier to follow in the code, and I think the JS code produced would be approximately the same.

> while there is just one way to compose two things, there isn't one way to decompose

When we compose two pieces into a single route (e.g. `final def /` in `PathSegment`), we capture the implicit `Composition` instance, and we use it for both compose and decompose. Since each of your Composition instances knows exactly how it does composition, it also knows how exactly to undo it, so I believe that we're safe from this concern.

@sherpal please let us know if you have objections to renaming the tuplez Composition's `unapply` method to `decompose`. Rationale: we have no `apply` method to match the `unapply` name with, and the `unapply` method's type signature makes it unusable from pattern matching in Scala anyway. I can make the required two-line change in url-dsl.

**Comment by sherpal** [comment]
I don't see any problem with that :) Thank you for the work!

**Comment by yurique** [comment]
@raquo it should be just a couple of lines to change in the code generator :) 

I'll release it as 0.3.x today.

**Comment by yurique** [comment]
> we capture the implicit Composition instance

Ah, cool! All should be good then.

**Comment by yurique** [comment]
@raquo https://github.com/tulz-app/tuplez/releases/tag/v0.3.8

**Comment by raquo** [comment]
Nice, thanks @yurique! I've made the small PR for this to URL-DSL, and I'm ready to update Waypoint whenever the new URL-DSL update is released.
