### ISSUE TITLE
endOfSegments should be the default behaviour

### ISSUE THREAD

**Issue by raquo** [sherpal/url-dsl#24]
Currently, when matching URL patterns, we need to specify `endOfSegments` to prevent the route from matching URLs that contain more segments than what the pattern contains. Over time I've seen several issues with that behaviour, both myself and raised by users ([example](https://github.com/raquo/Waypoint/issues/21)):
- Verbosity: (almost) all of my routes in all of my projects have `endOfSegments` in them
- Safety: Default behaviour without `endOfSegments` matches URLs that have more segments than what the pattern shows – this is non-obvious, and makes the routes sensitive to ordering (similar problems to putting a catch-all before other routes)
- Universality: `endOfSegments` can make sense as an instruction when matching URLs in a router, but I also want to use URL-DSL for other purposes, e.g. to build URLs for API endpoints in a type-safe manner. I don't need `endOfSegments` for this, so I'm inclined to use different patterns (with or without `endOfSegments`) based on use case, which is kinda confusing, and risky if my use case for a given url-dsl pattern changes over time (e.g. if I ever start matching those URL endpoints on the backend).

The current default behaviour for segments is consistent with the behaviour for query params, but I think those are different enough use cases to warrant specialized behaviour. Third party tools often add unexpected query params (e.g. for tracking), and even developers themselves often make some query params optional, but for segments both of those patterns are rather uncommon – for a given route, the number of segments is _usually_ set in stone, so that's a good default.

Proposal:
- `/ endOfSegments` should be eliminated / deprecated, and its behaviour should become the new default
- `/ remainingSegments` can still be used to capture the rest of segments
- Perhaps a new `/ ignoreRemainingSegments` could be implemented to reinstate the old match-and-ignore default behaviour
- We should also consider more compact naming that incorporates the term "rest", as that seems to be a common name for such things, e.g. `restSegments`, `ignoreRestSegments`.

What do you think?

**Comment by sherpal** [comment]
Thanks for the issue.

The `endOfSegments` thing is clearly a bit verbose and, if it should be the default for a user, clearly annoying to add.

I don't think we can reasonably make it a default for the `matchSegments` because that is the core thing that is used to compose stuff.
But, maybe, the `matchRawUrl` could "automatically" add the `endOfSegments` by default. And indeed we can implement a `ignoreRestSegments`.

My questions are:

1. what is the most inuitive when call `matchRawUrl`? I can definitively see that know the actual behaviour looking more like a "starts with" rather than a "==" can be confusing
2. I wonder how many people use this library "naked". That is, not as an underlying tool for something else (like a routing library). Because if the only use of the library is within an other tool, then that external tool can tweak the behaviour by automatically adding the `endOfSegments`.

In the end, even though it's a breaking change, I can see that changing the default behaviour of `matchRawUrl` (and adding a `ignoreRestSegments`) is the best approach.

**Comment by raquo** [comment]
Aha, I see what you mean about `matchSegments`.

`matchRawUrl` does seem to be the right place to address this.

> what is the most inuitive when call matchRawUrl? 

Personally, I would expect it to match more like `==` than like `startsWith`. At least for any use case I can think of.

I think the main use case for wanting `matchRawUrl` to ignore extra segments would be if you only cared about parsing the query params and didn't care about (most of) the segment path. But in that case it seems reasonable to say `ignoreRestSegments`, since that's what you want.

> how many people use this library "naked"

To support any "naked" use cases where the current behaviour of `matchRawUrl` is needed, we could add an optional `ignoreRestOfSegments: Boolean = false` argument to that method, or something like that. For non-"naked" use cases, the other change below can also be a solution.

> that external tool can tweak the behaviour by automatically adding the endOfSegments.

Indeed, I could in principle do it in Waypoint, but for that, I would need the ability to append `endOfSegments` to `PathSegmentWithQueryParams` – I can't do it with the exposed DSL, so we'd need to make the constructor params of `PathSegmentWithQueryParams` public. Actually that would probably be a good change anyway, for more advanced users. If we had that, I could start with it, hoping that end users won't find/need the public `UrlPart.matchRawUrl` method, although it would of course be nice if Waypoint behaviour matched raw URL-DSL behaviour.

**Comment by sherpal** [comment]
Hum, you are right that if you ask for the `PathSegmentWithQueryParams`, then you can't add this `endOfSegments`.

In any case, it's probably better if the `matchRawUrl` returns the `endOfSegmentRequired` error when there are remaining segments.

I will change that. Starting tomorrow I have 3 days without kids I home, I can't miss that opportunity!

On a retro compat side, it means that

- code that previously relied on the path not matching exactly will break :boom: :scream: 
- unfortunately I will need to embed the `endOfSegmentRequired` within the pathsegment... But that's ok because apart from `root` and `remainingSegments`, all the others already have access (at the construction side) to the error trait.

**Comment by raquo** [comment]
Awesome, thank you!

As far as migrations go, for end users, I think this one will be very reasonable. On my end I will of course inform Waypoint users about this in the changelog at the next release.

**Comment by sherpal** [comment]
I opened a draft pr for this. Maybe you can quickly take a look at the two places I mention in the description? 🙏
